path = r"C:\Users\Filip Pandic\repos\PrimaBarcode\app\src\main\java\com\prima\barcode\ui\screen\RecordingScreen.kt"
with open(path, "r", encoding="utf-8") as f:
    c = f.read()

old = (
    "@Composable\n"
    "private fun BigNumberLineRow(line: Line, onClick: () -> Unit) {\n"
    "    val sizeOffset = LocalTextSizeOffset.current\n"
    "    val statusColor = line.status.color\n"
    "    val isExact = line.status == LineStatus.EXACT\n"
    "    Row(\n"
    "        modifier = Modifier\n"
    "            .fillMaxWidth()\n"
    "            .height(IntrinsicSize.Min)\n"
    "            .background(statusColor.copy(alpha = 0.10f))\n"
    "            .clickable(onClick = onClick),\n"
    "        verticalAlignment = Alignment.CenterVertically,\n"
    "    ) {\n"
    "        Box(modifier = Modifier.width(6.dp).fillMaxHeight().background(statusColor))\n"
    "        Column(\n"
    "            modifier = Modifier.weight(1f).padding(start = 16.dp, top = 12.dp, bottom = 14.dp, end = 8.dp),\n"
    "        ) {\n"
    "            Text(line.item.no, style = monoLabel.copy(color = PrimaPalette.Ink3, fontSize = (12 + sizeOffset).sp))\n"
    "            Text(\n"
    "                line.item.name,\n"
    "                style = MaterialTheme.typography.bodyMedium.copy(\n"
    "                    fontWeight = FontWeight.Medium,\n"
    "                    fontSize = (15 + sizeOffset).sp,\n"
    "                    color = if (isExact) PrimaPalette.Ink3 else PrimaPalette.Ink,\n"
    "                    textDecoration = if (isExact) TextDecoration.LineThrough else TextDecoration.None,\n"
    "                ),\n"
    "                maxLines = 2,\n"
    "                overflow = TextOverflow.Ellipsis,\n"
    "            )\n"
    "        }\n"
    "        Row(verticalAlignment = Alignment.CenterVertically) {\n"
    "            Text(\n"
    "                line.scanned.formatQty(),\n"
    "                style = monoCounter.copy(color = statusColor, fontSize = (44 + sizeOffset).sp, fontWeight = FontWeight.Medium),\n"
    "            )\n"
    "            Text(\n"
    '                "/",\n'
    "                style = monoCounter.copy(color = statusColor.copy(alpha = 0.4f), fontSize = (44 + sizeOffset).sp),\n"
    "                modifier = Modifier.padding(horizontal = 4.dp),\n"
    "            )\n"
    "            Text(\n"
    "                line.expected.formatQty(),\n"
    "                style = monoCounter.copy(color = statusColor.copy(alpha = 0.7f), fontSize = (44 + sizeOffset).sp),\n"
    "            )\n"
    "        }\n"
    "        Icon(\n"
    "            Icons.Outlined.KeyboardArrowRight,\n"
    "            contentDescription = null,\n"
    "            tint = PrimaPalette.Ink3.copy(alpha = 0.55f),\n"
    "            modifier = Modifier.size(20.dp),\n"
    "        )\n"
    "        Spacer(Modifier.width(14.dp))\n"
    "    }\n"
    "}"
)

new = (
    "@Composable\n"
    "private fun BigNumberLineRow(line: Line, onClick: () -> Unit) {\n"
    "    val sizeOffset = LocalTextSizeOffset.current\n"
    "    val statusColor = line.status.color\n"
    "    Row(\n"
    "        modifier = Modifier\n"
    "            .fillMaxWidth()\n"
    "            .height(IntrinsicSize.Min)\n"
    "            .background(statusColor.copy(alpha = 0.10f))\n"
    "            .clickable(onClick = onClick),\n"
    "        verticalAlignment = Alignment.CenterVertically,\n"
    "    ) {\n"
    "        Box(modifier = Modifier.width(6.dp).fillMaxHeight().background(statusColor))\n"
    "        Column(\n"
    "            modifier = Modifier.weight(1f).padding(start = 16.dp, top = 16.dp, bottom = 18.dp, end = 8.dp),\n"
    "        ) {\n"
    "            Text(\n"
    "                line.item.no,\n"
    "                style = monoLabel.copy(\n"
    "                    color = PrimaPalette.Ink3,\n"
    "                    fontSize = (14 + sizeOffset).sp,\n"
    "                    textDecoration = TextDecoration.Underline,\n"
    "                ),\n"
    "            )\n"
    "            Text(\n"
    "                line.item.name,\n"
    "                style = MaterialTheme.typography.bodyMedium.copy(\n"
    "                    fontWeight = FontWeight.Medium,\n"
    "                    fontSize = (15 + sizeOffset).sp,\n"
    "                    color = if (line.status == LineStatus.EMPTY) PrimaPalette.Ink2 else PrimaPalette.Ink,\n"
    "                ),\n"
    "                maxLines = 2,\n"
    "                overflow = TextOverflow.Ellipsis,\n"
    "            )\n"
    "        }\n"
    "        Row(\n"
    "            modifier = Modifier.padding(end = 18.dp),\n"
    "            verticalAlignment = Alignment.CenterVertically,\n"
    "        ) {\n"
    "            Text(\n"
    "                line.scanned.formatQty(),\n"
    "                style = monoCounter.copy(color = statusColor, fontSize = (44 + sizeOffset).sp, fontWeight = FontWeight.Medium),\n"
    "            )\n"
    "            Text(\n"
    '                "/",\n'
    "                style = monoCounter.copy(color = statusColor.copy(alpha = 0.4f), fontSize = (44 + sizeOffset).sp),\n"
    "                modifier = Modifier.padding(horizontal = 4.dp),\n"
    "            )\n"
    "            Text(\n"
    "                line.expected.formatQty(),\n"
    "                style = monoCounter.copy(color = statusColor.copy(alpha = 0.7f), fontSize = (44 + sizeOffset).sp),\n"
    "            )\n"
    "        }\n"
    "    }\n"
    "}"
)

print("found:", old in c)
c = c.replace(old, new, 1)
with open(path, "w", encoding="utf-8") as f:
    f.write(c)
print("done")
